batch_around_ped: 256
batch_size: 8
clip: 1
config: hspa_1_2/hotel/star//config_train.yaml
dataset: eth5
early_stop: true
learning_rate: 0.0016
load_model_id: null
model_dir: hspa_1_2/hotel/star/
modelname: star
n_encoders: 2
n_layers: 1
num_epochs: 50
obs_length: 8
patience: 10
phase: train
randomRotate: true
sample_num: 20
save_base_dir: hspa_1_2
save_dir: hspa_1_2/hotel/
scheduler_method: Cosine
sendwx: true
seq_length: 20
test_set: hotel
using_cuda: true
